[package]
name = "verify-request-response"
publish = false
edition.workspace = true

[dependencies]
anyhow = { workspace = true }
tokio = { workspace = true }
ic-http-certification = { workspace = true }
ic-response-verification = "2.4"
ic-utils = "0.35"
ic-agent = "0.35"
